version: '3.5'

services:
  app-server:
    image: admarc/hydra:0.0.1
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/hydra?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SECURITY_SIGNING_KEY: fdsSA#Ffdss212F
      SECURITY_JWT_CLIENT_ID: hydraClient
      SECURITY_JWT_CLIENT_SECRET: dg7x4fkffKFKe3r3dfa
      SECURITY_JWT_GRANT_TYPE: password
      SECURITY_JWT_RESOURCE_IDS: hydraResourceIds
    networks:
      - backend

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: hydra
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend

volumes:
  db-data:

networks:
  backend:
