version: '3.5'

services:
  app-server:
    image: admarc/hydra:0.0.1
    ports:
      - "8081:8080"
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/hydra?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SECURITY_SIGNING_KEY: fdsSA#Ffdss212F
      SECURITY_JWT_CLIENT_ID: hydraClient
      SECURITY_JWT_CLIENT_SECRET: dg7x4fkffKFKe3r3dfa
      SECURITY_JWT_GRANT_TYPE: password
      SECURITY_JWT_RESOURCE_IDS: hydraResourceIds

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: hydra
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - app-data:/var/lib/mysql

  keycloak:
    image: jboss/keycloak:4.0.0.Final
    restart: on-failure
    command:
      - "-b"
      - "0.0.0.0"
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=dir"
      - "-Dkeycloak.migration.dir=/config/"
      - "-Dkeycloak.migration.strategy=IGNORE_EXISTING"
    volumes:
      - ./config:/config/
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
#      - KEYCLOAK_FRONTEND_URL='http://127.0.0.1:8080/auth'
      - DB_VENDOR=postgres
      - DB_USER=admin
      - DB_PASSWORD=password
      - DB_ADDR=keycloak-db
      - DB_PORT=5432
      - DB_DATABASE=keycloakdb
#      - KEYCLOAK_AUTH_URL=http://keycloak:8080/auth
    ports:
      - "8080:8080"
    depends_on:
      - keycloak-db

  keycloak-db:
    image: postgres:10
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloakdb
    volumes:
      - auth-data:/var/lib/postgresql/data

volumes:
  app-data:
  auth-data:

#  http://localhost:8080/auth/realms/hydra/protocol/openid-connect/auth?response_type=code&client_id=hydra-app&scope=openid&redirect_uri=http://localhost:8080/